### ISSUE TITLE
Issues with theme color schemes

### ISSUE THREAD

**Issue by jhardy1974** [Monnoroch/ColorHighlighter#166]
Hey guys, I started having problems with the plugin killing ST3. Here is the text from the message pop-up.

Error loading colour scheme Packages/User/Color Highlighter/themes/Flatland Monokai.tmTheme: Error parsing plist xml: expected element name in file Packages/User/Color Highlighter/themes/Flatland Monokai.tmTheme on line: 1259

**Comment by kevinchevallier** [comment]
Same here, it's a real nightmare:
error: Error loading colour scheme Packages/User/Color Highlighter/themes/predawn.tmTheme: Unable to open Packages/User/Color Highlighter/themes/predawn.tmTheme

Is there anyway to get rid of the plugin at all? I've already tried to switch back to a default theme and remove Colour highlighter via package control, no success.

**Comment by sebastienbarre** [comment]
It is indeed a nightmare, I've tried removing the plugin, all settings, caches, the error message persist, both in Sublime 2 and Sublime 3.

**Comment by jenn6** [comment]
I'm also having this problem. Tried to get rid of plugin, change themes, I even reinstalled ST3, nothings working. Any solutions?

**Comment by fritz-c** [comment]
I found something that worked for me -

#### Method A
Close all the files you currently have open, and restart Sublime once.

#### Method B (with explanation of the problem):
The underlying problem is the settings tied to Color Highlighter lingering in the Sublime session file. On Mac OS / Sublime Text 3, you can find it here:
```
~/Library/Application Support/Sublime Text 3/Local/Session.sublime_session
```
(If you're on a different system, just search Google for where to find that file on your setup.)

Close Sublime, open that session file in a __different__ text editor, and search for "Color Highlighter". For me it popped up under the settings for a couple files I always keep open. In my case, just closing those two files and then restarting Sublime was enough to fix the problem. If that's not working, editing the file to reflect your currently set theme would also work.

**Comment by Monnoroch** [comment]
Should be fixed in V7.

**Comment by alexortiz201** [comment]
Just recently had this issue, I used Package manager to uninstall and reinstall theme. Works now.

**Comment by gotofritz** [comment]
I have also solved that by editing that stuff out of `~/Library/Application Support/Sublime Text 3/Local/Session.sublime_session`

Must remember to do it in another editor, otherwise when you quit Sublime will recreate the strings you have deleted!

**Comment by LeonardoGentile** [comment]
This is not fixed.
It is a nightmare to remove this package.
I did solve by manually remove the entries from  `~/Library/Application Support/Sublime Text 3/Local/Session.sublime_session` with another editor

**Comment by taylorthurlow** [comment]
Same issue today. Got rid of the package and it kept popping up with an error. Spent 20 minutes trying to find vestiges of the plugin but couldn't find anything that would solve the problem. Thanks to @fritz-c I closed every open document I had, then closed ST3, then restarted ST3. It's gone now.
