### ISSUE TITLE
Feature request: highlight SASS color variables

### ISSUE THREAD

**Issue by bobrocke** [Monnoroch/ColorHighlighter#234]
I would like to have this package highlight sass/scss color variables in their defined colors.

Like this:

![www grav dev - atom](https://cloud.githubusercontent.com/assets/2962426/9028221/ed386e3a-393e-11e5-96b7-707decdfe673.jpg)

Edit:

Perhaps more explanation is needed. If the variable is defined within the file, it is properly colored. But if the definition is in another file, but within the project, it is not.

**Comment by Monnoroch** [comment]
Sould be fixed in brand new V7.

**Comment by bobrocke** [comment]
When will V7 show up as an update in Package Control?

**Comment by Monnoroch** [comment]
Already have!

**Comment by bobrocke** [comment]
It still does not color highlight variables who's definitions are in another file.

![theme scss brp](https://cloud.githubusercontent.com/assets/2962426/9420318/324c3fae-4832-11e5-9d4f-b4aaa8ab46a4.jpg)

v2015.08.21.17.15

**Comment by Monnoroch** [comment]
Yes, it does. You just need to either @import that another file, or put it into .sublime-project color_variables_file option.

**Comment by bobrocke** [comment]
Hmm. Mine won't even highlight variables with definitions in it's own file:

https://github.com/Monnoroch/ColorHighlighter/issues/246

**Comment by Monnoroch** [comment]
Hmm, okay, I usually test this feature on less, so I might miss something for sass.

**Comment by Monnoroch** [comment]
Fixed.
